### ISSUE TITLE
Pending session not visible

### ISSUE THREAD

**Issue by Isaac-Mander** [Isaac-Mander/TutorMe#113]
Session is in the future, yet doesn't show up on sessions page
![image](https://github.com/Isaac-Mander/TutorMe/assets/78179424/65397de6-e31c-4e00-84db-ca9d74379b8d)

![image](https://github.com/Isaac-Mander/TutorMe/assets/78179424/dc88bb6c-bfec-4faa-ac44-9e8114ff5d8c)

**Comment by Hellolightn3ss** [comment]
I haven't been able to replicate this issue, so will be closing it until further notice
